### ISSUE TITLE
verify the name of the  in kubectl apply -f install/kubernetes/istio-demo-auth.yaml

### ISSUE THREAD

**Issue by subhamkrai** [layer5io/istio-service-mesh-workshop#14]
verify of the file "kubectl apply -f install/kubernetes/istio-demo-auth.yaml" in [https://github.com/layer5io/istio-service-mesh-workshop/tree/master/lab-1#install-istio](https://github.com/layer5io/istio-service-mesh-workshop/tree/master/lab-1#install-istio)

**Comment by leecalcote** [comment]
Good eye. It looks like as of v1.4 Istio has removed that file and consolidated to istio-demo.yaml

**Comment by subhamkrai** [comment]
@leecalcote can we change the name of the file and it seems to be changed?

**Comment by leecalcote** [comment]
@subhamkrai, yes, please

**Comment by leecalcote** [comment]
Fixed by #20
