### ISSUE TITLE
need to remove repetition

### ISSUE THREAD

**Issue by subhamkrai** [layer5io/istio-service-mesh-workshop#15]
there is a duplicate entry  of "To verify istioctl is setup lets try to print out the command help" in
[https://github.com/layer5io/istio-service-mesh-workshop/tree/master/lab-1#-2---setting-up-istioctl](https://github.com/layer5io/istio-service-mesh-workshop/tree/master/lab-1#-2---setting-up-istioctl)

**Comment by leecalcote** [comment]
Bug! Good catch.
