### ISSUE TITLE
Visual updates for workshop page

### ISSUE THREAD

**Issue by nidhinmahesh** [layer5io/istio-service-mesh-workshop#21]
It would be better if we update the following elements in https://layer5.io/workshops page:

 - [ ] Moving animation for human actor animations
 - [ ] Affable newsletter box
 - [ ] Improved loading of other UI elements. 
 - [ ] Hover for details & rounded edge for workshop items. 
 - [ ] use Blue-white color pellet combination instead of grey-green (need discussion)

**Comment by leecalcote** [comment]
@nidhinmahesh the first four items sound great. Like you noted, the last item regarding a change of color combinations may be an improvement as well (needs a discussion). 

Note, that as some of the changes on these components are implemented, we will likely want to update their counterparts on other pages.

**Comment by nidhinmahesh** [comment]
Thanks @leecalcote for your suggestion.

**Comment by leecalcote** [comment]
@nidhinmahesh will you have a look at the newsletter box? It has a new graphic. What do you think?

**Comment by iambami** [comment]
This discussion has been clarified. I will be closing this issue now.
