### ISSUE TITLE
Update Labs examples

### ISSUE THREAD

**Issue by nveenjain** [layer5io/istio-service-mesh-workshop#22]
The current labs are outdated and don't show the current version istio outputs

The following fixes needs to be done:-

### LAB 2
https://github.com/layer5io/istio-service-mesh-workshop/tree/master/lab-2#verify-the-namespace-is-labelled In example output, row should be updated to 
```
istio-system   Active    1h        disabled 
```
Mannual Installation needs to be updated.

### LAB 4
Istio bytes count is available in prometheus instead of istio_request_count, screenshot needs to be updated

### LAB 6
Output format of both [6.1](https://github.com/layer5io/istio-service-mesh-workshop/tree/master/lab-6#61-inject-a-route-rule-to-create-a-fault-using-http-delay) and [6.2](https://github.com/layer5io/istio-service-mesh-workshop/tree/master/lab-6#62-inject-a-route-rule-to-create-a-fault-using-http-abort) has changed. Now Percentage, and value is used instead of percent field.

### LAB 7
Screenshot needs to be updated, since it shows 0 queries per second

### LAB 8
(needs to be discussed) Simple Http call worked
Call with/without certificate didn't, but error is different (ssl3_get record: wrong version number)
This needs to be looked into.

**Comment by leecalcote** [comment]
Good eye, @nveenjain. // @kanishkarj @shivaylamba
