### ISSUE TITLE
Lab 8: TLS error is different under Istio v1.5

### ISSUE THREAD

**Issue by leecalcote** [layer5io/istio-service-mesh-workshop#25]
The error output is no longer:

```
curl: (35) gnutls_handshake() failed: Handshake failed
```

**Comment by nveenjain** [comment]
The error is : 
```curl: (7) Failed to connect to details port 9080: Connection timed out```
when in PERMISSIVE mode with PeerAuthentication set

the error output when no certificates are present:

```curl: (16) SSL_write() returned SYSCALL, errno = 104```

Command to run to set PeerAuthentication:-

```sh
kubectl apply -f - <<EOF
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
spec:
  mtls:
    mode: STRICT
EOF

```
