### ISSUE TITLE
prereq/README.md: command to start mesheryctl should be `mesheryctl system start` instead of `mesheryctl start`

### ISSUE THREAD

**Issue by daksh-sagar** [layer5io/istio-service-mesh-workshop#32]
Running `mesheryctl start` throws `Error: invalid command "start"`.

> Can you please provide a better description for the issue?
> Like where this change needs to happen?
Of course. In `prereq/README.md` file.

**Comment by Nikhil-Ladha** [comment]
Can you please provide a better description for the issue?
Like where this change needs to happen?

**Comment by leecalcote** [comment]
Good catch. Fixed.
