### ISSUE TITLE
Istio install fails

### ISSUE THREAD

**Issue by anwarchk** [layer5io/istio-service-mesh-workshop#34]
**Description**
Followed the step `istioctl install --set profile=demo`

✘ Egress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the conditionsystem/istio-ingressgateway
Deployment/istio-system/istio-egressgateway
✘ Ingress gateways encountered an error: failed to wait for resource: resources not ready after 5m0s: timed out waiting for the condition
Deployment/istio-system/istio-ingressgateway

**Expected Behavior**

Istio is installed successfully

**Screenshots**

**Environment:**
 - OS: Mac OSX

K8s details

Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

[Optional] **Additional Context**

**Comment by anwarchk** [comment]
Step in the install `https://github.com/layer5io/istio-service-mesh-workshop/blob/master/lab-1/README.md#1.1`

**Comment by anwarchk** [comment]
`kubectl describe pod istio-ingressgateway-768ff847df-7c45p` returns  

```
 Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  38m                    default-scheduler  Successfully assigned istio-system/istio-ingressgateway-768ff847df-7c45p to minikube-m03
  Normal   Pulling    38m                    kubelet            Pulling image "docker.io/istio/proxyv2:1.9.0"
  Normal   Pulled     38m                    kubelet            Successfully pulled image "docker.io/istio/proxyv2:1.9.0" in 8.288537294s
  Normal   Created    38m                    kubelet            Created container istio-proxy
  Normal   Started    38m                    kubelet            Started container istio-proxy
  Warning  Unhealthy  37m (x21 over 38m)     kubelet            Readiness probe failed: Get "http://10.244.2.4:15021/healthz/ready": dial tcp 10.244.2.4:15021: connect: connection refused
  Warning  Unhealthy  3m37s (x994 over 36m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 50```

**Comment by leecalcote** [comment]
@anwarchk thanks much for raising this issue. Good feedback.

Looking over the command executed, I wonder if it isn't missing `-n Istio-system` (the namespace in which the gateway will be deployed).

**Comment by iambami** [comment]
@leecalcote I believe this issue is resolved and can be closed now, if not can it be assigned to someone else?

**Comment by AugustasV** [comment]
Closing this now. Feel free reopen if issue reappears @anwarchk
