### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/istio-service-mesh-workshop#43]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Resources**

**Alternatives / Additional Context**

**Comment by namitarjaria** [comment]
Hey, I would love to work on this issue.

**Comment by HetviSoni** [comment]
Assigning it to you @depleur

**Comment by namitarjaria** [comment]
Feel free to correct me but after some research, I figured that there's no code in this repository that actually needs for this issue to be raised. @thisiskaransgit you can close this issue unless I've gone wrong.

**Comment by thisiskaransgit** [comment]
@depleur  thanks for pointing this out, since we are missing other times, kindly add them too in the issue templates at the bottom 
```
<h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).
```

**Comment by thisiskaransgit** [comment]
@depleur, I've updated the issue description with the desired Figma link

**Comment by namitarjaria** [comment]
> @depleur, I've updated the issue description with the desired Figma link

Okay, I'll work on this then, thanks.

**Comment by abhijeetgauravm** [comment]
Can u assign me @thisiskaransgit ?

**Comment by thisiskaransgit** [comment]
since we haven't heard back or seen any progress from @depleur, @abhijeetgauravm go ahead and please update promptly 🚀
