### ISSUE TITLE
Incorrect link on Main Workshop Page

### ISSUE THREAD

**Issue by alainvanhoof** [layer5io/istio-service-mesh-workshop#6]
The link to Observability -> Lab 6 - Distributed Tracing, is 404. 
It is pointing to: 
https://github.com/leecalcote/istio-service-mesh-workshop/blob/master/lab-4a/README.md 
but this should be:
https://github.com/leecalcote/istio-service-mesh-workshop/tree/master/lab-6/README.md

**Comment by leecalcote** [comment]
Thank you, @alainvanhoof!

**Comment by leecalcote** [comment]
Thanks again, @alainvanhoof. This link was fixed by commit https://github.com/leecalcote/istio-service-mesh-workshop/commit/78567f0f7751f4051740710bd703746ef81d55b2 by @girishranganathan.
